// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABWI4gCQnwNoWM6R5jXfd1YZtlM-YLRrc',
    appId: '1:640665556059:web:8c5111f7e1e5d76efa5b7e',
    messagingSenderId: '640665556059',
    projectId: 'auth-f8bd3',
    authDomain: 'auth-f8bd3.firebaseapp.com',
    storageBucket: 'auth-f8bd3.appspot.com',
    measurementId: 'G-T6KBGJL9QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMuc8Bzi_cwibPhajv1SU-OAeUokYI-mA',
    appId: '1:640665556059:android:459ed6b361767d65fa5b7e',
    messagingSenderId: '640665556059',
    projectId: 'auth-f8bd3',
    storageBucket: 'auth-f8bd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvRdIDTEA7B65-DdGZwBmsU1ZO3bbvCaE',
    appId: '1:640665556059:ios:efb18d10d766e3e7fa5b7e',
    messagingSenderId: '640665556059',
    projectId: 'auth-f8bd3',
    storageBucket: 'auth-f8bd3.appspot.com',
    iosBundleId: 'com.example.loginsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvRdIDTEA7B65-DdGZwBmsU1ZO3bbvCaE',
    appId: '1:640665556059:ios:efb18d10d766e3e7fa5b7e',
    messagingSenderId: '640665556059',
    projectId: 'auth-f8bd3',
    storageBucket: 'auth-f8bd3.appspot.com',
    iosBundleId: 'com.example.loginsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABWI4gCQnwNoWM6R5jXfd1YZtlM-YLRrc',
    appId: '1:640665556059:web:e3586ff1c32c2e31fa5b7e',
    messagingSenderId: '640665556059',
    projectId: 'auth-f8bd3',
    authDomain: 'auth-f8bd3.firebaseapp.com',
    storageBucket: 'auth-f8bd3.appspot.com',
    measurementId: 'G-82X03YNRZ5',
  );
}
