// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxE8N7Adb0CgbaFfFbFbc7c4rjT9qIq8M',
    appId: '1:244155355784:web:1899ec24de77af1f85053d',
    messagingSenderId: '244155355784',
    projectId: 'loginandsignup-cbfa5',
    authDomain: 'loginandsignup-cbfa5.firebaseapp.com',
    storageBucket: 'loginandsignup-cbfa5.appspot.com',
    measurementId: 'G-1HLHLXY30D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQDC79Cm0xJwJCq9lVIbN4axg3Wmwf5Js',
    appId: '1:244155355784:android:c3dd703ebe7a01fa85053d',
    messagingSenderId: '244155355784',
    projectId: 'loginandsignup-cbfa5',
    storageBucket: 'loginandsignup-cbfa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ergN8CtiNWk05vYjhT73OZrcxvcWRAM',
    appId: '1:244155355784:ios:93f474eb67517de385053d',
    messagingSenderId: '244155355784',
    projectId: 'loginandsignup-cbfa5',
    storageBucket: 'loginandsignup-cbfa5.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ergN8CtiNWk05vYjhT73OZrcxvcWRAM',
    appId: '1:244155355784:ios:93f474eb67517de385053d',
    messagingSenderId: '244155355784',
    projectId: 'loginandsignup-cbfa5',
    storageBucket: 'loginandsignup-cbfa5.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxE8N7Adb0CgbaFfFbFbc7c4rjT9qIq8M',
    appId: '1:244155355784:web:67d232ad2ca8ae9e85053d',
    messagingSenderId: '244155355784',
    projectId: 'loginandsignup-cbfa5',
    authDomain: 'loginandsignup-cbfa5.firebaseapp.com',
    storageBucket: 'loginandsignup-cbfa5.appspot.com',
    measurementId: 'G-KJT6W9H4RB',
  );
}
